# Generated by Django 6.0.2 on 2026-03-03 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='created_at',
            new_name='created_At',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='created_at',
            new_name='created_At',
        ),
    ]
