# Generated by Django 6.0.2 on 2026-03-12 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_productimage_color_alter_productimage_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='whatsapp_number',
            field=models.CharField(default='temp', max_length=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product', 'color')},
        ),
    ]
