# Generated by Django 6.0.2 on 2026-03-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_product_image_order_city_order_postal_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='uploaded_At',
        ),
        migrations.AddField(
            model_name='productimage',
            name='color',
            field=models.CharField(default='temp', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productimage',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
