# Generated by Django 6.0.2 on 2026-03-17 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order_whatsapp_number_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='color',
            field=models.CharField(default='temp', max_length=50),
            preserve_default=False,
        ),
    ]
